name: Learning Lab Automator

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt
        
      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run : echo $commitmsg

      - name: Execute Python script
        run: |
          python scripts/learninglabauto.py

      - name: commit changes
        run: |
          chmod +x ./scripts/commit.sh
          ./scripts/commit.sh
